apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  # namespace: roboshop
  labels:
    app: nginx
    demo: service
spec:
# containers is a list of containers
  containers:
  - name: nginx-pod
    image: nginx
    # here with this line port will not be opened.
    ports:
    - containerPort: 80
###

    
