apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  # namespace: roboshop
  labels:
    app: nginx
    demo: service
spec:
# containers is a list of containers
  containers:
  - name: nginx-pod
    image: nginx
    # here with this line port will not be opened.
    ports:
    - containerPort: 80
---
# pod is created up, to what should be the service attatched to ? below is the service definition
# for the above pod
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
# what should the service be attached to ? labels must be unique otherwise it will be attached to the wrong pod
# if nothing is provided it means its a clutster ip
spec:
  selector:
    app: nginx
    demo: service
# the following means that if someone hits the service on port 80 , it will be redirected to container.
  ports:
  - protocol: TCP
    port: 80 #service port
    targetPort: 80 # container port

