apiVersion: v1
kind: nodeport
metadata:
  name: nginx-nodeport
  # namespace: roboshop
  labels:
    app: nginx-nodeport
    demo: service
spec:
# containers is a list of containers
  containers:
  - name: nginx-nodeport
    image: nginx
    # here with this line port will not be opened.
    ports:
    - containerPort: 80
---
# nodeport is created up, to what should be the service attatched to ? below is the service definition
# for the above nodeport
apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport
# what should the service be attached to ? labels must be unique otherwise it will be attached to the wrong nodeport
# if nothing is provided it means its a clutster ip
spec:
  type: NodePort
  selector:
    app: nginx-nodeport
    demo: service
# the following means that if someone hits the service on port 80 , it will be redirected to container.
  ports:
  - protocol: TCP
    port: 80 #service port
    targetPort: 80 # container port

