apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-dynamic
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 4Gi
---
# i need to attatch with pod the pv 
apiVersion: v1
kind: Pod
metadata:
  name: app
  labels:
    demo: ebs-dynamic
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: nginx-data
      mountPath: /usr/share/nginx/html
  nodeSelector:
    zone: 1f # because we labeled our instances as 1f (since they are in 1f zone) and we want to deploy our pod in the same zone, if not volume will not be mounted because its in different zone
  volumes:
  - name: nginx-data
    persistentVolumeClaim:
      claimName: ebs-dynamic
---
apiVersion: v1
kind: Service
metadata:
  name: ebs-dynamic
spec:
  type: LoadBalancer
  selector:
    demo: ebs-static
  ports:
  - protocol: TCP
    port: 80 #service-port
    targetPort: 80 #container-port