apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
  labels:
    app: nginx
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 3
  selector: # replica-set labels . we've sepecified 3 replica , the selection of pod for the replica set will be done by labels below
    matchLabels:
      app: nginx
      tier: frontend
  template: # pod definition / pod template, pod is a subset of replica set so it starts from here
    metadata:
      labels:
        app: nginx
        tier: frontend
    spec:
      containers:
      - name: nignx
        image: nginx
