apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
  # namespace: roboshop
spec:
# containers is a list of containers
  containers:
  - name: hello-pod
    image: nginx
    ports:
    - containerPort: 80
