apiVersion: v1
kind: Pod
metadata:
  name: multi-container
spec:
# containers is a list of containers
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
  - name: almalinux
    image:  almalinux:8
    # alma linux will fail so we have to make it for some time
    command: ["sleep", "300"]

