apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
  # namespace: roboshop
spec:
  containers:
  - name: hello-pod
    image: nginx
    # here with this line port will not be opened.
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
  - name: log-aggregator