apiVersion: v1
kind: Pod
metadata:
  name: config-pod
  namespace: roboshop
spec:
# containers is a list of containers
  containers:
  - name: config-pod
    image: nginx
    ports:
    - containerPort: 80
    env:
    - name: course
      # value: devops
      # instead of hard coding the value like above we can use configmap
      valueFrom:
        configMapKeyRef:
          name: devops-config
          key: course
    - name: trainer
      valueFrom:
        configMapKeyRef:
          name: devops-config
          key: trainer
    
